name = "rehydrate-site"
compatibility_date = "2025-10-18"

# Required for Pages
pages_build_output_dir = "_site"

# Environment variables (optional)
[vars]
CACHE_MAX_AGE = "3600"

# Bind your R2 bucket
[[r2_buckets]]
binding = "PODCAST_BUCKET"
bucket_name = "rehydratepodcast"

# Local dev (optional)
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"
