name = "rehydrate-worker"
main = "worker.js"
compatibility_date = "2025-10-18"
pages_build_output_dir = "_site"

# Route all requests to the Worker
routes = [
  { pattern = "rehydratepodcast-github-io.pages.dev/*", zone_name = "rehydratepodcast-github-io.pages.dev" }
]

# Bind your R2 bucket
[[r2_buckets]]
binding = "PODCAST_BUCKET"
bucket_name = "rehydratepodcast"

# Optional: Environment variables
[vars]
CACHE_MAX_AGE = "3600"

# Dev mode
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"
